version: '3'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:8080"
    depends_on:
      - db

  db:
    image: postgres:alpine
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - "dbdata:/var/lib/postgresql/data"
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"

volumes:
  dbdata: {}